[package]
name = "xtask"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
rust-version.workspace = true
publish.workspace = true
repository.workspace = true
description = "Repository automation for Summoners"

[dependencies]
chrono.workspace = true
clap.workspace = true
color-eyre.workspace = true
summoners_cards = { path = "../crates/cards" }
summoners_core = { path = "../crates/core" }
summoners_match_log = { path = "../crates/match-log" }

[lints]
workspace = true
