[package]
name = "cceroby"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
rust-version.workspace = true
publish.workspace = true
repository.workspace = true
description = "Local museum image search for Summoners card art."

[dependencies]
axum.workspace = true
clap.workspace = true
color-eyre.workspace = true
serde.workspace = true
serde_urlencoded.workspace = true
thiserror.workspace = true
tokio.workspace = true
webbrowser.workspace = true

[dev-dependencies]
tower = { version = "0.5", features = ["util"] }

[lints]
workspace = true
