//! Git hook lifecycle for the lint pipeline.
//!
//! One hook is managed: `pre-commit`. It delegates to
//! `cargo xtask lint --staged-only`, so the hook script never has to
//! change when a check is added or removed.

use std::env;
use std::fs;
use std::io::ErrorKind;
use std::path::{Path, PathBuf};
use std::process::Command;

use color_eyre::eyre::{Result, WrapErr, eyre};

/// Every hook this task owns.
const HOOKS: &[&str] = &["pre-commit"];

/// The hook script. It is deliberately tiny: the decisions live in Rust.
const PRE_COMMIT_SCRIPT: &str = "\
#!/bin/sh
# Generated by: cargo xtask lint --install-hooks
exec cargo xtask lint --staged-only
";

/// Facts needed to decide if one directory entry belongs to this task.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
enum HookEntryFacts {
    Missing,
    Symlink,
    Other,
    Regular {
        canonical_content: bool,
        executable: bool,
    },
}
/// Ownership state for safe status and removal decisions.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
enum HookOwnership {
    Missing,
    Managed,
    Unmanaged,
}

/// Decide ownership without touching the filesystem.
fn classify_hook(facts: HookEntryFacts) -> HookOwnership {
    match facts {
        HookEntryFacts::Missing => HookOwnership::Missing,
        HookEntryFacts::Regular {
            canonical_content: true,
            executable: true,
        } => HookOwnership::Managed,
        HookEntryFacts::Symlink | HookEntryFacts::Other | HookEntryFacts::Regular { .. } => {
            HookOwnership::Unmanaged
        }
    }
}

/// Resolve the path printed by Git against the workspace root.
fn resolve_reported_git_path(root: &Path, reported: &str) -> Option<PathBuf> {
    let reported = reported.trim();
    if reported.is_empty() {
        return None;
    }
    let path = Path::new(reported);
    Some(if path.is_absolute() {
        path.to_path_buf()
    } else {
        root.join(path)
    })
}

/// Build one collision suffix for a hook backup.
fn backup_path(path: &Path, stamp: &str, attempt: u32) -> PathBuf {
    let extension = if attempt == 0 {
        format!("backup.{stamp}")
    } else {
        format!("backup.{stamp}.{attempt}")
    };
    path.with_extension(extension)
}

/// The directory the task runs from, which must be the workspace root.
fn project_root() -> Result<PathBuf> {
    env::current_dir().wrap_err("failed to read the current workspace directory")
}

/// Ask Git for the active hooks directory.
///
/// `git rev-parse --git-path hooks` handles normal repositories, linked
/// worktrees, and `core.hooksPath`. Its output can be relative or absolute.
fn resolve_hooks_dir(root: &Path) -> Result<PathBuf> {
    let output = Command::new("git")
        .current_dir(root)
        .args(["rev-parse", "--git-path", "hooks"])
        .output()
        .wrap_err("failed to ask git for the hooks directory")?;
    if !output.status.success() {
        return Err(eyre!(
            "git could not resolve the hooks directory (status {}): {}",
            output.status,
            String::from_utf8_lossy(&output.stderr).trim()
        ));
    }
    let reported = String::from_utf8_lossy(&output.stdout);
    resolve_reported_git_path(root, &reported)
        .ok_or_else(|| eyre!("git returned an empty hooks directory"))
}

/// Read filesystem facts, without following symlinks, then decide ownership.
fn inspect_hook(path: &Path) -> Result<HookOwnership> {
    let metadata = match fs::symlink_metadata(path) {
        Ok(metadata) => metadata,
        Err(error) if error.kind() == ErrorKind::NotFound => {
            return Ok(classify_hook(HookEntryFacts::Missing));
        }
        Err(error) => {
            return Err(error)
                .wrap_err_with(|| format!("failed to inspect hook {}", path.display()));
        }
    };

    let facts = if metadata.file_type().is_symlink() {
        HookEntryFacts::Symlink
    } else if metadata.is_file() {
        let content =
            fs::read(path).wrap_err_with(|| format!("failed to read hook {}", path.display()))?;
        #[cfg(unix)]
        let executable = {
            use std::os::unix::fs::PermissionsExt;
            metadata.permissions().mode() & 0o111 != 0
        };
        #[cfg(not(unix))]
        let executable = true;

        HookEntryFacts::Regular {
            canonical_content: content == PRE_COMMIT_SCRIPT.as_bytes(),
            executable,
        }
    } else {
        HookEntryFacts::Other
    };

    Ok(classify_hook(facts))
}

/// Move any directory entry aside, including a symlink, before installation.
fn backup_existing_hook(path: &Path, hook: &str) -> Result<()> {
    match fs::symlink_metadata(path) {
        Ok(_) => {
            let stamp = format!(
                "{}_{}",
                chrono::Local::now().format("%Y%m%d_%H%M%S_%f"),
                std::process::id()
            );
            let mut attempt = 0;
            let backup = loop {
                let candidate = backup_path(path, &stamp, attempt);
                match fs::symlink_metadata(&candidate) {
                    Err(error) if error.kind() == ErrorKind::NotFound => break candidate,
                    Ok(_) => attempt += 1,
                    Err(error) => {
                        return Err(error).wrap_err_with(|| {
                            format!("failed to inspect backup path {}", candidate.display())
                        });
                    }
                }
            };
            fs::rename(path, &backup).wrap_err_with(|| {
                format!(
                    "failed to back up existing {hook} hook to {}",
                    backup.display()
                )
            })?;
            println!("backed up existing {hook} -> {}", backup.display());
            Ok(())
        }
        Err(error) if error.kind() == ErrorKind::NotFound => Ok(()),
        Err(error) => Err(error)
            .wrap_err_with(|| format!("failed to inspect existing hook {}", path.display())),
    }
}

/// Write the hook, keeping a timestamped copy of anything already there.
pub fn install_hooks() -> Result<()> {
    let root = project_root()?;
    let hooks_dir = resolve_hooks_dir(&root)?;
    fs::create_dir_all(&hooks_dir)
        .wrap_err_with(|| format!("failed to create hooks directory {}", hooks_dir.display()))?;

    for hook in HOOKS {
        let hook_path = hooks_dir.join(hook);
        backup_existing_hook(&hook_path, hook)?;
        fs::write(&hook_path, PRE_COMMIT_SCRIPT)
            .wrap_err_with(|| format!("failed to write hook {}", hook_path.display()))?;

        #[cfg(unix)]
        {
            use std::os::unix::fs::PermissionsExt;
            fs::set_permissions(&hook_path, fs::Permissions::from_mode(0o755)).wrap_err_with(
                || format!("failed to make hook executable: {}", hook_path.display()),
            )?;
        }

        println!("installed {hook} hook");
    }
    Ok(())
}

/// Remove one hook only when its exact content and mode prove ownership.
fn uninstall_hook(path: &Path) -> Result<HookOwnership> {
    let ownership = inspect_hook(path)?;
    if ownership == HookOwnership::Managed {
        fs::remove_file(path)
            .wrap_err_with(|| format!("failed to remove managed hook {}", path.display()))?;
    }
    Ok(ownership)
}

/// Remove the managed hook. Missing and unmanaged entries stay unchanged.
pub fn uninstall_hooks() -> Result<()> {
    let root = project_root()?;
    let hooks_dir = resolve_hooks_dir(&root)?;

    for hook in HOOKS {
        let hook_path = hooks_dir.join(hook);
        match uninstall_hook(&hook_path)? {
            HookOwnership::Managed => println!("removed {hook} hook"),
            HookOwnership::Missing => println!("no {hook} hook found"),
            HookOwnership::Unmanaged => {
                println!("{hook}: unmanaged hook left unchanged")
            }
        }
    }
    Ok(())
}

/// Report whether the exact managed hook is in place.
pub fn show_status() -> Result<()> {
    let root = project_root()?;
    let hooks_dir = resolve_hooks_dir(&root)?;

    for hook in HOOKS {
        let hook_path = hooks_dir.join(hook);
        let status = match inspect_hook(&hook_path)? {
            HookOwnership::Managed => "installed",
            HookOwnership::Missing => "not installed",
            HookOwnership::Unmanaged => "unmanaged",
        };
        println!("{hook}: {status}");
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    #![allow(clippy::unwrap_used, clippy::expect_used)]

    use std::fs;
    use std::path::PathBuf;

    use super::{
        HookEntryFacts, HookOwnership, PRE_COMMIT_SCRIPT, backup_existing_hook, backup_path,
        classify_hook, resolve_reported_git_path, uninstall_hook,
    };

    fn temporary_directory(name: &str) -> PathBuf {
        let path = std::env::temp_dir().join(format!(
            "summoners-xtask-{name}-{}-{}",
            std::process::id(),
            chrono::Utc::now().timestamp_nanos_opt().unwrap()
        ));
        fs::create_dir_all(&path).unwrap();
        path
    }

    #[test]
    fn the_managed_hook_uses_the_canonical_wrapper() {
        assert_eq!(
            PRE_COMMIT_SCRIPT,
            "#!/bin/sh\n\
# Generated by: cargo xtask lint --install-hooks\n\
exec cargo xtask lint --staged-only\n"
        );
    }

    #[test]
    fn ownership_requires_exact_content_and_executable_mode() {
        assert_eq!(
            classify_hook(HookEntryFacts::Regular {
                canonical_content: true,
                executable: true,
            }),
            HookOwnership::Managed
        );
        for facts in [
            HookEntryFacts::Missing,
            HookEntryFacts::Symlink,
            HookEntryFacts::Other,
            HookEntryFacts::Regular {
                canonical_content: false,
                executable: true,
            },
            HookEntryFacts::Regular {
                canonical_content: true,
                executable: false,
            },
        ] {
            assert_ne!(classify_hook(facts), HookOwnership::Managed);
        }
    }

    #[test]
    fn git_paths_can_be_relative_absolute_or_empty() {
        let root = PathBuf::from("/workspace");
        assert_eq!(
            resolve_reported_git_path(&root, ".git/hooks\n"),
            Some(root.join(".git/hooks"))
        );
        assert_eq!(
            resolve_reported_git_path(&root, "/tmp/custom-hooks\n"),
            Some(PathBuf::from("/tmp/custom-hooks"))
        );
        assert_eq!(resolve_reported_git_path(&root, " \n"), None);
    }

    #[test]
    fn backup_paths_add_an_attempt_instead_of_reusing_a_name() {
        let hook = PathBuf::from("/repo/hooks/pre-commit");
        assert_eq!(
            backup_path(&hook, "stamp", 0),
            PathBuf::from("/repo/hooks/pre-commit.backup.stamp")
        );
        assert_eq!(
            backup_path(&hook, "stamp", 2),
            PathBuf::from("/repo/hooks/pre-commit.backup.stamp.2")
        );
    }

    #[test]
    fn uninstall_does_not_remove_an_unmanaged_hook() {
        let directory = temporary_directory("unmanaged-hook");
        let hook = directory.join("pre-commit");
        fs::write(&hook, "#!/bin/sh\necho custom\n").unwrap();

        assert_eq!(uninstall_hook(&hook).unwrap(), HookOwnership::Unmanaged);
        assert_eq!(
            fs::read_to_string(&hook).unwrap(),
            "#!/bin/sh\necho custom\n"
        );

        fs::remove_dir_all(directory).unwrap();
    }

    #[cfg(unix)]
    #[test]
    fn backing_up_a_symlink_does_not_overwrite_its_target() {
        use std::os::unix::fs::symlink;

        let directory = temporary_directory("symlink-hook");
        let target = directory.join("target");
        let hook = directory.join("pre-commit");
        fs::write(&target, "keep me\n").unwrap();
        symlink(&target, &hook).unwrap();

        backup_existing_hook(&hook, "pre-commit").unwrap();
        fs::write(&hook, PRE_COMMIT_SCRIPT).unwrap();

        assert_eq!(fs::read_to_string(&target).unwrap(), "keep me\n");
        assert_eq!(fs::read_to_string(&hook).unwrap(), PRE_COMMIT_SCRIPT);
        assert!(
            fs::read_dir(&directory)
                .unwrap()
                .filter_map(Result::ok)
                .any(|entry| entry
                    .file_name()
                    .to_string_lossy()
                    .starts_with("pre-commit.backup."))
        );

        fs::remove_dir_all(directory).unwrap();
    }
}

#[cfg(test)]
mod lint_pipeline_tests {
    #![allow(clippy::unwrap_used, clippy::expect_used)]

    use super::super::{
        CHECKS, CheckId, CheckOutcome, CheckResult, LintArgs, MAX_FILE_LINES,
        STAGED_RUST_DIFF_ARGS, UNSTAGED_RUST_DIFF_ARGS, check_display_name, determine_outcome,
        evaluate_file_lengths, evaluate_too_many_args, fix_args, format_log_entry,
        is_tool_not_found, line_forbids_too_many_args, partially_staged_files,
        scan_file_for_too_many_args, should_skip, structural_source,
    };

    fn lint_args() -> LintArgs {
        LintArgs {
            verbose: false,
            no_fmt: false,
            no_check: false,
            no_clippy: false,
            no_test: false,
            no_file_length: false,
            no_too_many_args: false,
            fix: false,
            staged_only: false,
            install_hooks: false,
            uninstall_hooks: false,
            hooks_status: false,
        }
    }

    fn output_of(outcome: &CheckOutcome) -> String {
        match outcome {
            CheckOutcome::Passed { output } | CheckOutcome::Failed { output } => output.clone(),
            CheckOutcome::Skipped => String::new(),
        }
    }

    fn is_failure(outcome: &CheckOutcome) -> bool {
        matches!(outcome, CheckOutcome::Failed { .. })
    }

    #[test]
    fn a_missing_tool_reads_as_absent_not_unhappy() {
        assert!(is_tool_not_found("error: no such command: `nextest`\n"));
        assert!(is_tool_not_found("bash: cargo-nextest: not found\n"));
        assert!(is_tool_not_found("No such file or directory\n"));
        assert!(is_tool_not_found("error: unrecognized subcommand 'lint'\n"));
    }

    #[test]
    fn an_ordinary_failure_does_not_read_as_a_missing_tool() {
        assert!(!is_tool_not_found("error[E0308]: mismatched types\n"));
        assert!(!is_tool_not_found("warning: unused variable\n"));
        assert!(!is_tool_not_found(""));
    }

    #[test]
    fn only_an_optional_check_can_skip() {
        let optional = determine_outcome(false, "not found\n".to_string(), true);
        assert!(matches!(optional, CheckOutcome::Skipped));

        let required = determine_outcome(false, "not found\n".to_string(), false);
        assert!(is_failure(&required));

        let happy = determine_outcome(true, String::new(), true);
        assert!(matches!(happy, CheckOutcome::Passed { .. }));
    }

    #[test]
    fn a_log_entry_carries_the_name_and_the_output() {
        let result = CheckResult {
            name: "cargo fmt -- --check".to_string(),
            outcome: CheckOutcome::Passed {
                output: "all good\n".to_string(),
            },
        };
        assert_eq!(
            format_log_entry(&result),
            "=== cargo fmt -- --check ===\nall good\n\n"
        );

        let skipped = CheckResult {
            name: "cargo nextest".to_string(),
            outcome: CheckOutcome::Skipped,
        };
        assert!(format_log_entry(&skipped).contains("[skipped"));
    }

    #[test]
    fn fix_mode_writes_for_fmt_and_clippy_only() {
        assert_eq!(fix_args(CheckId::Fmt), Some(vec!["fmt"]));
        assert!(
            fix_args(CheckId::Clippy)
                .unwrap()
                .contains(&"--allow-dirty")
        );
        assert_eq!(fix_args(CheckId::Check), None);
        assert_eq!(fix_args(CheckId::Test), None);
        assert_eq!(fix_args(CheckId::FileLength), None);
        assert_eq!(fix_args(CheckId::TooManyArgsAllow), None);
    }

    #[test]
    fn the_pipeline_contract_is_exact() {
        let definitions = CHECKS
            .iter()
            .map(|check| {
                (
                    check.id,
                    check.name,
                    check.program,
                    check.args,
                    check.optional,
                )
            })
            .collect::<Vec<_>>();
        assert_eq!(
            definitions,
            vec![
                (
                    CheckId::Fmt,
                    "cargo fmt -- --check",
                    "cargo",
                    &["fmt", "--", "--check"][..],
                    false,
                ),
                (
                    CheckId::Check,
                    "cargo check --workspace --all-targets",
                    "cargo",
                    &["check", "--workspace", "--all-targets"][..],
                    false,
                ),
                (
                    CheckId::Clippy,
                    "cargo clippy --workspace --all-targets -- -D warnings",
                    "cargo",
                    &[
                        "clippy",
                        "--workspace",
                        "--all-targets",
                        "--",
                        "-D",
                        "warnings",
                    ][..],
                    false,
                ),
                (
                    CheckId::Test,
                    "cargo test --workspace --all-targets",
                    "cargo",
                    &["test", "--workspace", "--all-targets"][..],
                    false,
                ),
                (
                    CheckId::FileLength,
                    "file length (<= 1000 lines)",
                    "__builtin__",
                    &[][..],
                    false,
                ),
                (
                    CheckId::TooManyArgsAllow,
                    "forbid #[allow(clippy::too_many_arguments)]",
                    "__builtin__",
                    &[][..],
                    false,
                ),
            ]
        );
    }

    #[test]
    fn each_skip_flag_controls_only_its_check() {
        type SkipCase = (CheckId, fn(&mut LintArgs));
        let cases: [SkipCase; 6] = [
            (CheckId::Fmt, |args: &mut LintArgs| args.no_fmt = true),
            (CheckId::Check, |args: &mut LintArgs| args.no_check = true),
            (CheckId::Clippy, |args: &mut LintArgs| {
                args.no_clippy = true;
            }),
            (CheckId::Test, |args: &mut LintArgs| args.no_test = true),
            (CheckId::FileLength, |args: &mut LintArgs| {
                args.no_file_length = true;
            }),
            (CheckId::TooManyArgsAllow, |args: &mut LintArgs| {
                args.no_too_many_args = true;
            }),
        ];

        for (selected, enable) in cases {
            let mut args = lint_args();
            enable(&mut args);
            for check in CHECKS {
                assert_eq!(should_skip(check.id, &args), check.id == selected);
            }
        }
    }

    #[test]
    fn non_skip_flags_do_not_skip_checks() {
        let args = LintArgs {
            verbose: true,
            no_fmt: false,
            no_check: false,
            no_clippy: false,
            no_test: false,
            no_file_length: false,
            no_too_many_args: false,
            fix: true,
            staged_only: true,
            install_hooks: true,
            uninstall_hooks: true,
            hooks_status: true,
        };
        assert!(CHECKS.iter().all(|check| !should_skip(check.id, &args)));
    }

    #[test]
    fn a_display_name_joins_the_program_and_its_arguments() {
        assert_eq!(check_display_name("cargo", &["fmt"]), "cargo fmt");
        assert_eq!(check_display_name("cargo", &[]), "cargo");
    }

    #[test]
    fn a_file_at_the_limit_passes_and_one_over_it_fails() {
        let at_limit = [("crates/core/src/render.rs".to_string(), MAX_FILE_LINES)];
        assert!(!is_failure(&evaluate_file_lengths(
            &at_limit,
            MAX_FILE_LINES
        )));

        let over = [("crates/core/src/render.rs".to_string(), MAX_FILE_LINES + 1)];
        let outcome = evaluate_file_lengths(&over, MAX_FILE_LINES);
        assert!(is_failure(&outcome));
        assert!(output_of(&outcome).contains("render.rs (1001 lines)"));
    }

    #[test]
    fn an_empty_workspace_passes_the_length_check() {
        assert!(!is_failure(&evaluate_file_lengths(&[], MAX_FILE_LINES)));
    }

    #[test]
    fn the_ban_reads_an_attribute_and_ignores_prose() {
        assert!(line_forbids_too_many_args(
            "#[allow(clippy::too_many_arguments)]"
        ));
        assert!(line_forbids_too_many_args(
            "    #[allow(dead_code, clippy::too_many_arguments)]"
        ));
        assert!(line_forbids_too_many_args(
            "#![allow(clippy::too_many_arguments)]"
        ));

        assert!(!line_forbids_too_many_args(
            "/// Never write #[allow(clippy::too_many_arguments)] here."
        ));
        assert!(!line_forbids_too_many_args(
            "let text = \"#[allow(clippy::too_many_arguments)]\";"
        ));
        assert!(!line_forbids_too_many_args("#[allow(dead_code)]"));
        assert!(!line_forbids_too_many_args(
            "#[deny(clippy::too_many_arguments)]"
        ));
    }

    #[test]
    fn the_ban_reads_a_multiline_allow_attribute() {
        let source = "\
#[allow(
    dead_code,
    clippy::too_many_arguments,
)]
fn wide(a: u8) -> u8 { a }
";
        let findings = scan_file_for_too_many_args("lib.rs", source);
        assert_eq!(findings.len(), 1);
        assert_eq!(findings[0].line, 1);
    }

    #[test]
    fn a_test_module_may_allow_what_the_crate_may_not() {
        let source = "\
#[allow(clippy::too_many_arguments)]
fn wide(a: u8) -> u8 { a }

#[cfg(test)]
mod tests {
    #[allow(clippy::too_many_arguments)]
    fn also_wide(a: u8) -> u8 { a }
}
";
        let findings = scan_file_for_too_many_args("lib.rs", source);
        assert_eq!(findings.len(), 1);
        assert_eq!(findings[0].line, 1);

        let outcome = evaluate_too_many_args(&findings);
        assert!(is_failure(&outcome));
        assert!(output_of(&outcome).contains("lib.rs:1"));
    }

    #[test]
    fn a_clean_file_passes_the_ban() {
        let findings = scan_file_for_too_many_args("lib.rs", "fn narrow() {}\n");
        assert!(findings.is_empty());
        assert!(!is_failure(&evaluate_too_many_args(&findings)));
    }

    #[test]
    fn braces_in_test_literals_and_comments_do_not_hide_production_allows() {
        let source = r####"
#[cfg(test)]
mod tests {
    const TEXT: &str = "}";
    const RAW: &str = r#"}"#;
    const BRACE: char = '}';
    // }
    /* } */
}

#[allow(clippy::too_many_arguments)]
fn production(a: u8) -> u8 { a }
"####;
        let findings = scan_file_for_too_many_args("lib.rs", source);
        assert_eq!(findings.len(), 1);
        assert_eq!(findings[0].line, 11);
    }

    #[test]
    fn structural_scanning_preserves_code_and_line_numbers() {
        let source = "fn main() {\n  let text = \"}\"; // }\n}\n";
        let structural = structural_source(source);
        assert_eq!(structural.lines().count(), source.lines().count());
        assert_eq!(structural.matches('{').count(), 1);
        assert_eq!(structural.matches('}').count(), 1);
    }

    #[test]
    fn partial_staging_is_the_ordered_intersection() {
        let staged = vec!["a.rs".to_string(), "b.rs".to_string(), "c.txt".to_string()];
        let unstaged = vec![
            "other.rs".to_string(),
            "b.rs".to_string(),
            "a.rs".to_string(),
        ];
        assert_eq!(
            partially_staged_files(&staged, &unstaged),
            vec!["a.rs".to_string(), "b.rs".to_string()]
        );
        assert!(partially_staged_files(&staged, &[]).is_empty());
    }

    #[test]
    fn staged_queries_include_renames_and_all_unstaged_changes() {
        assert_eq!(
            STAGED_RUST_DIFF_ARGS,
            [
                "diff",
                "--cached",
                "--name-only",
                "--diff-filter=ACMR",
                "--",
            ]
        );
        assert_eq!(UNSTAGED_RUST_DIFF_ARGS, ["diff", "--name-only", "--"]);
    }

    #[test]
    fn a_test_only_file_may_allow_too_many_arguments() {
        let source = "#![cfg(test)]\n#![allow(clippy::too_many_arguments)]\nfn wide() {}\n";
        assert!(scan_file_for_too_many_args("tests.rs", source).is_empty());
    }
}
